# -*- coding: utf-8 -*-
"""Plate Number Detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zuo0r_akcAB5KtPKvJmNwpCmILyq3s80

## Import Dataset menggunakan API Roboflow
"""

!pip install ultralytics

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="This Key Using API Roboflow")
project = rf.workspace("roboflow-universe-projects").project("license-plate-recognition-rxg4e")
version = project.version(4)
dataset = version.download("yolov8")

import os
from ultralytics import YOLO
# Load a model
model = YOLO("yolov8n.yaml")  # build a new model from scratch

# Use the model
results = model.train(data="dataset.yaml", epochs=15)  # train the model